---
- hosts: all
  sudo: yes
  remote_user: pi
  tasks:
    - name: change locale to POSIX
      command: update-locale LANG=POSIX
      ignore_errors: yes

    - name: remove large files
      command: rm -rf {{item}}
      with_items:
        - "/opt/*"

    - name: remove unused packages
      apt: name={{item}} state=absent purge=yes update_cache=yes
      with_items:
        - aptitude
        - aptitude-common
        - binutils
        - bsdmainutils
        - cpio
        - cpp
        - cpp-4.9
        - curl
        - dc
        - dialog
        - dpkg-dev
        - ed
        - fakeroot
        - fbset
        - gcc-4.6-base:armhf
        - gcc-4.7-base:armhf
        - gcc-4.8-base:armhf
        - gdb
        - gdbserver
        - geoip-database
        - groff-base
        - hardlink
        - info
        - keyboard-configuration
        - krb5-locales
        - less
        - libasan1
        - libasound2-data
        - libasound2
        - libatomic1
        - libc-dev-bin
        - libc6-dbg
        - libc6-dev
        - libfakeroot
        - libfreetype6
        - libfreetype6-dev
        - libgcc-4.9-dev
        - libgcc-4.9-dev
        - libgcc1:armhf
        - libglib2.0-0
        - libgomp1
        - libicu52
        - libpng12-dev
        - libraspberrypi-dev
        - libraspberrypi-doc
        - libsamplerate0
        - libstdc++-4.9-dev
        - libtext-soundex-perl
        - libubsan0
        - libx11-6
        - libx11-data
        - libxapian22
        - libxau6
        - libxcb1
        - libxdmcp6
        - linux-libc-dev
        - locales
        - lsb-release
        - lua5.1
        - luajit
        - makedev
        - man-db
        - manpages
        - manpages-dev
        - ncdu
        - ncurses-term
        - netcat-openbsd
        - netcat-traditional
        - parted
        - perl
        - perl-modules
        - plymouth
        - psmisc
        - python-apt
        - python-apt-common
        - python-rpi.gpio
        - rename
        - samba-common
        - strace
        - tasksel
        - tasksel-data
        - traceroute
        - triggerhappy
        - unzip
        - v4l-utils
        - vim-common
        - vim-tiny
        - whiptail
        - xkb-data
        - zlib1g-dev

    - name: apt-get autoremove
      command: apt-get -y autoremove

    - name: apt-get clean
      command: apt-get -y clean

    - name: reboot
      command: reboot
