---
- hosts: all
  sudo: yes
  remote_user: pi
  tasks:
    - name: change locale to POSIX
      command: update-locale LANG=POSIX
      ignore_errors: yes

    - name: remove large files
      command: rm -rf {{item}}
      with_items:
        - "/opt/*"

    - name: remove unused packages
      apt: name={{item}} state=absent purge=yes update_cache=yes
      with_items:
        - libglib2.0-0
        - krb5-locales
        - geoip-database
        - rename
        - strace
        - perl
        - perl-modules
        - locales
        - binutils
        - libicu52
        - gdb
        - gdbserver
        - groff-base
        - netcat-openbsd
        - netcat-traditional
        - plymouth
        - samba-common
        - tasksel
        - tasksel-data
        - traceroute
        - vim-common
        - vim-tiny
        - whiptail
        - man-db
        - manpages
        - dpkg-dev
        - libc-dev-bin
        - libc6-dev:armhf
        - libfreetype6-dev
        - libgcc-4.9-dev:armhf
        - libpng12-dev:armhf
        - libraspberrypi-dev
        - libstdc++-4.9-dev:armhf
        - linux-libc-dev:armhf
        - manpages-dev
        - zlib1g-dev:armhf
        - libx11-6:armhf
        - libx11-data
        - libpython-stdlib:armhf
        - libpython2.7:armhf
        - libpython2.7-minimal:armhf
        - libpython2.7-stdlib:armhf
        - python-apt
        - python-apt-common
        - python-rpi.gpio
        - libasound2:armhf
        - libasound2-data
        - libtext-soundex-perl
        - gcc-4.6-base:armhf
        - gcc-4.7-base:armhf
        - gcc-4.8-base:armhf
        - libgcc-4.9-dev:armhf
        - libgcc1:armhf
        - libraspberrypi-doc
        - keyboard-configuration
        - xkb-data
        - triggerhappy
        - lsb-release
        - libxau6:armhf
        - libxcb1:armhf
        - libxdmcp6:armhf
        - libubsan0:armhf
        - libsamplerate0:armhf
        - libgomp1:armhf
        - libfreetype6:armhf
        - libfakeroot:armhf
        - libasan1:armhf
        - libatomic1:armhf
        - fakeroot
        - cpp
        - cpp-4.9
        - libc6-dbg

    - name: apt-get autoremove
      command: apt-get -y autoremove

    - name: apt-get clean
      command: apt-get -y clean
      
    - name: reboot
      command: reboot
